//$file${..\Appli\App::HttpServer.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: Server.qm
// File:  ${..\Appli\App::HttpServer.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${..\Appli\App::HttpServer.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "main.h"
#include "qpc.h"

#include "main_app.h"
#include "HttpServer.h"

#include "logging.h"

//$declare${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Server} .............................................................
typedef struct Server {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;

// public:
} Server;

extern Server Server_inst;

// protected:
static QState Server_initial(Server * const me, void const * const par);
static QState Server_down(Server * const me, QEvt const * const e);
static QState Server_up(Server * const me, QEvt const * const e);
//$enddecl${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Server} .......................................................
QActive * const AO_Server = &Server_inst.super;

//${Shared::Server_ctor} .....................................................
void Server_ctor(void) {
    Server * const me = &Server_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Server_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


//$define${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Server} .............................................................
Server Server_inst;

//${AOs::Server::SM} .........................................................
static QState Server_initial(Server * const me, void const * const par) {
    //${AOs::Server::SM::initial}
    (void)par; // unused parameter


    //QTimeEvt_armX(&me->timeEvt,
    //BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);

    QS_FUN_DICTIONARY(&Server_down);
    QS_FUN_DICTIONARY(&Server_up);

    return Q_TRAN(&Server_down);
}

//${AOs::Server::SM::down} ...................................................
static QState Server_down(Server * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Server::SM::down}
        case Q_ENTRY_SIG: {
            HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_RESET);

            //Create the initial start  event for the server
            QACTIVE_POST(AO_Server, Q_NEW(QEvt, SERVER_START_SIG), (void)0U);

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Server::SM::down}
        case Q_EXIT_SIG: {
            //HAL_GPIO_WritePin(LED_RED_GPIO_Port, LED_RED_Pin, GPIO_PIN_SET);

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Server::SM::down::SERVER_START}
        case SERVER_START_SIG: {
            //ASSERT THE cHIP ENABLE GPIO PIN
            HAL_GPIO_WritePin(CHIP_EN_GPIO_Port, CHIP_EN_Pin, GPIO_PIN_SET);

            status_ = Q_TRAN(&Server_up);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Server::SM::up} .....................................................
static QState Server_up(Server * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Server::SM::up}
        case Q_ENTRY_SIG: {
            HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_SET);

            //Initialise the wifi module, LWIP networkstack, logging system and the shell service
            main_app();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Server::SM::up::SERVER_STOP}
        case SERVER_STOP_SIG: {
            status_ = Q_TRAN(&Server_down);
            break;
        }
        //${AOs::Server::SM::up::ST67_INIT_FAIL}
        case ST67_INIT_FAIL_SIG: {
              LogInfo("##### Wifi init failure end\n");

            status_ = Q_TRAN(&Server_down);
            break;
        }
        //${AOs::Server::SM::up::SERVER_LISTEN}
        case SERVER_LISTEN_SIG: {
            LogInfo("##### WE ARE GOOD TO GO –🫡🫡\n");

            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

