//$file${..\Appli\App::HttpServer.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: Server.qm
// File:  ${..\Appli\App::HttpServer.c}
//
// This code has been generated by QM 7.0.2 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${..\Appli\App::HttpServer.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include <string.h>
#include <inttypes.h>

#include "main.h"
#include "qpc.h"
#include "FreeRTOS.h"
#include "w6x_api.h"
#include "logging.h"

#include "common_parser.h" /* Common Parser functions */
#include "shell.h"

#include "app_config.h"
#include "main_app.h"
#include "HttpServer.h"
#include "HttpService.h"
#include "event_groups.h"

/** Priority of the user pins polling task */
#define PIN_POLLING_THREAD_PRIO        30

/** Stack size of the user pins polling task */
#define PIN_POLLING_TASK_STACK_SIZE    512

/** Priority of the web server child task */
#define WEBSERVER_CHILD_THREAD_PRIO    29

/** Stack size of the web server child task */
#define HTTP_CHILD_TASK_STACK_SIZE     2048

/** HTTP server port */
#define HTTP_PORT                      80

/** Socket timeout in ms */
#define SOCKET_TIMEOUT_MS              1000

/** Maximum bytes to send in one step */
#define MAX_BYTES_TO_SEND              4096

extern EventGroupHandle_t pin_handle;

//$declare${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Server} .............................................................
typedef struct Server {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;

// public:

// private:
    int32_t ret;
    int32_t sock;
    struct sockaddr_in s_addr_in_t;
    uint8_t ip_addr[4];

// public:
    uint8_t netmask_addr[4];

// private:
    int32_t timeout;
    int32_t fct_start;
} Server;

extern Server Server_inst;

// protected:
static QState Server_initial(Server * const me, void const * const par);
static QState Server_down(Server * const me, QEvt const * const e);
static QState Server_up(Server * const me, QEvt const * const e);
//$enddecl${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Server} .......................................................
QActive * const AO_Server = &Server_inst.super;

//${Shared::Server_ctor} .....................................................
void Server_ctor(void) {
    Server * const me = &Server_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Server_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


//$define${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Server} .............................................................
Server Server_inst;

//${AOs::Server::SM} .........................................................
static QState Server_initial(Server * const me, void const * const par) {
    //${AOs::Server::SM::initial}
    (void)par; // unused parameter


    //QTimeEvt_armX(&me->timeEvt,
    //BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);

    QS_FUN_DICTIONARY(&Server_down);
    QS_FUN_DICTIONARY(&Server_up);

    return Q_TRAN(&Server_down);
}

//${AOs::Server::SM::down} ...................................................
static QState Server_down(Server * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Server::SM::down}
        case Q_ENTRY_SIG: {
            HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_RESET);

            //Create the initial start  event for the server
            QACTIVE_POST(AO_Server, Q_NEW(QEvt, SERVER_START_SIG), (void)0U);

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Server::SM::down}
        case Q_EXIT_SIG: {
            //HAL_GPIO_WritePin(LED_RED_GPIO_Port, LED_RED_Pin, GPIO_PIN_SET);

            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Server::SM::down::SERVER_START}
        case SERVER_START_SIG: {
            //ASSERT THE cHIP ENABLE GPIO PIN
            HAL_GPIO_WritePin(CHIP_EN_GPIO_Port, CHIP_EN_Pin, GPIO_PIN_SET);

            status_ = Q_TRAN(&Server_up);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Server::SM::up} .....................................................
static QState Server_up(Server * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Server::SM::up}
        case Q_ENTRY_SIG: {
            HAL_GPIO_WritePin(LED_GREEN_GPIO_Port, LED_GREEN_Pin, GPIO_PIN_SET);

            //Initialise the wifi module, LWIP networkstack, logging system and the shell service
            main_app();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Server::SM::up::SERVER_STOP}
        case SERVER_STOP_SIG: {
            status_ = Q_TRAN(&Server_down);
            break;
        }
        //${AOs::Server::SM::up::ST67_INIT_FAIL}
        case ST67_INIT_FAIL_SIG: {
              LogInfo("##### Wifi init failure end\n");

            status_ = Q_TRAN(&Server_down);
            break;
        }
        //${AOs::Server::SM::up::SERVER_LISTEN}
        case SERVER_LISTEN_SIG: {
            //if(me->sock > 0 && !me->ret){
                /*Just listen for incomming connection requests on the socket*/
                //goto _listen;

            //}

            LogInfo("##### WE ARE GOOD TO GO –🫡🫡\n");
            W6X_WiFi_ApConfig_t ap_config = {0};

            /* Start soft-AP */
            ap_config.Channel = WIFI_SAP_CHANNEL;
            ap_config.Security = W6X_WIFI_AP_SECURITY_WPA3_PSK;
            ap_config.MaxConnections = WIFI_SAP_MAX_CONNECTIONS;
            ap_config.Protocol = W6X_WIFI_PROTOCOL_11AX;
            strncpy((char *)ap_config.SSID, WIFI_SAP_SSID, W6X_WIFI_MAX_SSID_SIZE);
            strncpy((char *)ap_config.Password, WIFI_SAP_PASSWORD, W6X_WIFI_MAX_PASSWORD_SIZE);
            me->ret = W6X_WiFi_AP_Start(&ap_config);

            if (me->ret)
            {
                LogError("Failed to start soft-AP, %" PRIi32 "\n", me->ret);
                goto _err;
            }
            else
            {
                LogInfo("Soft-AP started\n");
            }

            /* Get the soft-AP current IP address */
            me->ret = W6X_Net_AP_GetIPAddress(me->ip_addr, me->netmask_addr);

            if (me->ret != W6X_STATUS_OK)
            {
                LogError("Get soft-AP IP failed\n");
                goto _err;
            }

            LogInfo("Soft-AP IP address : " IPSTR "\n", IP2STR(me->ip_addr));
            me->s_addr_in_t.sin_addr.s_addr = ATON(me->ip_addr);
            me->s_addr_in_t.sin_port = PP_HTONS(HTTP_PORT);
            me->s_addr_in_t.sin_family = AF_INET;


            /* Create a new TCP server socket with port HTTP_PORT */
            me->sock = W6X_Net_Socket(AF_INET, SOCK_STREAM, IPPROTO_TCP);
            if (me->sock < 0)
            {
                LogInfo("Could not create the socket.\n");
                me->ret= W6X_STATUS_OK + 1;
                goto _err;
            }


            //_sock_config:
                /* Socket present*/

                /* Set the socket Receive timeout option */
                me->ret = W6X_Net_Setsockopt(me->sock, SOL_SOCKET, SO_RCVTIMEO, (void *)&me->timeout, sizeof(me->timeout));
                if (me->ret != 0)
                {
                    LogError("Could not set the socket options.\n");
                    goto _err;
                }

                /* Set the socket Send timeout option */
                me->ret = W6X_Net_Setsockopt(me->sock, SOL_SOCKET, SO_SNDTIMEO, (void *)&me->timeout, sizeof(me->timeout));
                if (me->ret != 0)
                {
                    LogError("Could not set the socket options.\n");
                    goto _err;
                }

                /* Set the socket Send timeout option */
                me->ret = W6X_Net_Setsockopt(me->sock, SOL_SOCKET, SO_KEEPALIVE, (void *)&me->timeout, sizeof(me->timeout));
                if (me->ret != 0)
                {
                    LogError("Could not set the socket options.\n");
                    goto _err;
                }

                /* Bind the socket to the server address */
                me->ret = W6X_Net_Bind(me->sock, (struct sockaddr *)&me->s_addr_in_t, sizeof(me->s_addr_in_t));

                if (me->ret != 0)
                {
                    LogInfo("\n LwIP Bind Fail\n");
                    goto _err;
                }

                LogInfo("\n LwIP Bind Pass\n");

            //_listen:
                /* Listen for incoming connections (TCP listen backlog = 5). */
                me->ret = W6X_Net_Listen(me->sock, 5);

                if (me->ret != 0)
                {
                    LogInfo("\n LwIP Listen Fail\n");
                    goto _err;
                }

                LogInfo("\n LwIP Listening\n");

              /* Creation of a thread to check if the pin value of the button or the LEDs has change */
              pin_handle = xEventGroupCreate();
              if (pdPASS != xTaskCreate((TaskFunction_t)pin_verification_task, "UserPinsPolling",
                                        PIN_POLLING_TASK_STACK_SIZE >> 2,
                                        &me->fct_start, PIN_POLLING_THREAD_PRIO, NULL))
              {
                LogInfo("User pins task creation failed\n");
                goto _err;
              }


              while (1)
              {
                struct sockaddr remotehost_t;
                uint32_t remotehost_size = sizeof(remotehost_t);

                /* Wait for an incoming client connection */
                int32_t newconn = W6X_Net_Accept(me->sock, (struct sockaddr *)&remotehost_t, (socklen_t *)&remotehost_size);
                if (newconn < 0)
                {
                  vTaskDelay(200);
                  LogInfo("\n Failed to accept new client requests.\n");
                }
                else
                {
                  /* Create a temporary thread to process the incoming HTTP request */
                  char thread_name[14];
                  const size_t thread_name_len = sizeof(thread_name);
                  snprintf(thread_name, thread_name_len, "HTTP_%08" PRIX32, newconn);
                  thread_name[thread_name_len - 1] = '\0';

                  LogDebug("\n Creation of temporary thread to process an incoming HTTP request : %" PRIi32 "\n", newconn);
                  if (pdPASS != xTaskCreate((TaskFunction_t)http_server_serve_task, thread_name,
                                            HTTP_CHILD_TASK_STACK_SIZE >> 2,
                                            &newconn, WEBSERVER_CHILD_THREAD_PRIO, NULL))
                  {
                    LogInfo("%s task creation failed\n", thread_name);
                  }
                  /* Delay added to avoid that too many requests are processed in parallel */
                  vTaskDelay(50);
                }
              }



            _err:
              /* Error case 1*/
              if ((me->sock >= 0) && (W6X_Net_Shutdown(me->sock, 1) != W6X_STATUS_OK))
              {
                LogError("Failed to close server socket\n");

              }else{
                LogInfo("Socket closed\n");

              }

                /* De-initialize the ST67W6X Network module */
                W6X_Net_DeInit();

                /* De-initialize the ST67W6X Wi-Fi module */
                W6X_WiFi_DeInit();

                /* De-initialize the ST67W6X Driver */
                W6X_DeInit();

                shell_freertos_deinit();

                LogInfo("##### Sever Application end\n");

                //Create the initial start  event for the server
                QACTIVE_POST(AO_Server, Q_NEW(QEvt, ST67_INIT_FAIL_SIG), (void)0U);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
//$enddef${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

